---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: db
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      labels:
        type: db
        author: intelliqit
  template:
    metadata:
      name: mysql-pod
      labels: 
        type: db
        author: intelliqit
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password 
...
