---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: intelliqit
spec:
  type: LoadBalancer
  ports: 
    - tagetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: proxy 
...
