---
apiVersion: apps/v1
kind: Statefulset
metadata:
  name: mysql
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
    template:
      metadata:
        labels:
        app: mysql
      spec:
        volumes:
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: task-pv-claim
        containers:
          - name: mysql
            image: mysql:5
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: intelliqit
            ports:
              - name: tcp
                protocal: TCP
                containerPort: 3306
            volumeMounts:
              - name: task-pv-storage
                mountPath: /var/lib/mysql
...

